Packit rpm
containers/crun-vm pull request #15
Opened 2024-01-16 11:31 UTC by lsm5

depends on https://github.com/containers/crun-vm/pull/14

2024-01-16 12:07 UTC, rhatdan commented on .packit.yaml
> +      epel-8-x86_64: {}
I don't think we should support RHEL8 only 9 and later

2024-01-17 15:22 UTC, lsm5 commented
rust on rhel9 is 1.71 while crun-vm needs 1.74. Disabling epel build targets for now.

2024-01-17 15:46 UTC, lsm5 commented
Good to go. rpm built in copr installs `/usr/bin/crun-vm`. Once this is merged, crun-vm will be built automatically on `rhcontainerbot/podman-next` after each commit to main. Might wanna review and merge #14 first for Makefile.

2024-01-17 15:49 UTC, lsm5 commented
Also, might wanna consider doing a 0.0.1 release or whatever to get official Fedora packaging going. Not a requirement but could be nice to have instead of just building a commit id.

2024-01-18 10:19 UTC, albertofaria requested changes

2024-01-18 10:19 UTC, albertofaria commented on rpm/crun-vm.spec
> +License: Apache-2.0 AND MIT AND Zlib
This probably has to be: `(Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (MIT OR Apache-2.0) AND (MIT OR Unlicense) AND Apache-2.0 AND GPL-2.0-or-later AND MIT AND MPL-2.0 AND MPL-2.0+ AND Unicode-DFS-2016`

2024-01-18 10:19 UTC, albertofaria commented on .packit.yaml
> +upstream_tag_template: v{version}
I cut a 0.1.0 release now. The tag doesn't have a `v` prefix.

2024-01-18 10:19 UTC, albertofaria commented on rpm/crun-vm.spec
> +Source0: %{url}/archive/v%{version}.tar.gz
Also need to drop the `v` prefix here.

2024-01-26 11:34 UTC, rhatdan commented
@lsm5 Needs a rebase.

2024-01-26 11:59 UTC, lsm5 commented
Added unit test runs on each target using TMT. lmk if it's overkill.

2024-01-26 13:02 UTC, lsm5 commented
@albertofaria @rhatdan PTAL

2024-01-26 13:07 UTC, albertofaria approved these changes

2024-01-26 13:07 UTC, albertofaria commented
Thanks, LGTM.

2024-01-26 13:07 UTC, merged

2024-01-26 15:03 UTC, lsm5 commented
crun-vm is now installable via `rhcontainerbot/podman-next` copr.

2024-01-26 15:52 UTC, rhatdan commented
We are off to the races.
Now to get it into Fedora...